"""update_game_session_stats

Revision ID: da37cd902f0c
Revises: fa984ffcf9b1
Create Date: 2026-08-18 00:45:55.820477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da37cd902f0c'
down_revision: Union[str, None] = 'fa984ffcf9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('system_integrity', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('game_sessions', sa.Column('corruption_level', sa.Integer(), nullable=False, server_default='20'))
    op.add_column('game_sessions', sa.Column('debug_energy', sa.Integer(), nullable=False, server_default='100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_sessions', 'current_chapter',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('game_sessions', 'debug_energy')
    op.drop_column('game_sessions', 'corruption_level')
    op.drop_column('game_sessions', 'system_integrity')
    # ### end Alembic commands ###
