"""create_initial_schema

Revision ID: fa984ffcf9b1
Revises: 
Create Date: 2026-08-18 00:39:51.058134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa984ffcf9b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_fragments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('integrity', sa.Float(), nullable=False),
    sa.Column('chapter', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_fragments_memory_key'), 'memory_fragments', ['memory_key'], unique=True)
    op.create_table('quests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quest_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('chapter', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_quest_key'), 'quests', ['quest_key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('discovered_memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_fragments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_memories_memory_id'), 'discovered_memories', ['memory_id'], unique=False)
    op.create_index(op.f('ix_discovered_memories_user_id'), 'discovered_memories', ['user_id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_chapter', sa.String(length=50), nullable=False),
    sa.Column('current_sector', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_id'), 'game_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.create_table('player_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('system_integrity', sa.Integer(), nullable=False),
    sa.Column('corruption_level', sa.Integer(), nullable=False),
    sa.Column('debug_energy', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_profiles_user_id'), 'player_profiles', ['user_id'], unique=True)
    op.create_table('quest_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('quest_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_progress_quest_id'), 'quest_progress', ['quest_id'], unique=False)
    op.create_index(op.f('ix_quest_progress_user_id'), 'quest_progress', ['user_id'], unique=False)
    op.create_table('game_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_events_event_type'), 'game_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_game_events_session_id'), 'game_events', ['session_id'], unique=False)
    op.create_table('save_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('game_session_id', sa.String(length=36), nullable=True),
    sa.Column('save_name', sa.String(length=100), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('serialized_game_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_save_slots_game_session_id'), 'save_slots', ['game_session_id'], unique=False)
    op.create_index(op.f('ix_save_slots_user_id'), 'save_slots', ['user_id'], unique=False)
    op.create_table('world_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('object_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_objects_object_id'), 'world_objects', ['object_id'], unique=False)
    op.create_index(op.f('ix_world_objects_session_id'), 'world_objects', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_objects_session_id'), table_name='world_objects')
    op.drop_index(op.f('ix_world_objects_object_id'), table_name='world_objects')
    op.drop_table('world_objects')
    op.drop_index(op.f('ix_save_slots_user_id'), table_name='save_slots')
    op.drop_index(op.f('ix_save_slots_game_session_id'), table_name='save_slots')
    op.drop_table('save_slots')
    op.drop_index(op.f('ix_game_events_session_id'), table_name='game_events')
    op.drop_index(op.f('ix_game_events_event_type'), table_name='game_events')
    op.drop_table('game_events')
    op.drop_index(op.f('ix_quest_progress_user_id'), table_name='quest_progress')
    op.drop_index(op.f('ix_quest_progress_quest_id'), table_name='quest_progress')
    op.drop_table('quest_progress')
    op.drop_index(op.f('ix_player_profiles_user_id'), table_name='player_profiles')
    op.drop_table('player_profiles')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_discovered_memories_user_id'), table_name='discovered_memories')
    op.drop_index(op.f('ix_discovered_memories_memory_id'), table_name='discovered_memories')
    op.drop_table('discovered_memories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quests_quest_key'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_memory_fragments_memory_key'), table_name='memory_fragments')
    op.drop_table('memory_fragments')
    # ### end Alembic commands ###
